/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Todo API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customFetcher } from './fetcher';
export interface Todo {
  id?: number;
  title?: string;
  description?: string;
  completed?: boolean;
}

export type AddTodoBody = {
  title: string;
  description?: string;
};

export type UpdateTodoBody = {
  completed?: boolean;
};

/**
 * @summary 할 일 목록 조회
 */
export const getTodos = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetcher<Todo[]>(
      {url: `/api/todos`, method: 'GET', signal
    },
      );
    }
  



export const getGetTodosQueryKey = () => {
    return [
    `/api/todos`
    ] as const;
    }

    
export const getGetTodosQueryOptions = <TData = Awaited<ReturnType<typeof getTodos>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTodosQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTodos>>> = ({ signal }) => getTodos(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTodosQueryResult = NonNullable<Awaited<ReturnType<typeof getTodos>>>
export type GetTodosQueryError = unknown


export function useGetTodos<TData = Awaited<ReturnType<typeof getTodos>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodos>>,
          TError,
          Awaited<ReturnType<typeof getTodos>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTodos<TData = Awaited<ReturnType<typeof getTodos>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodos>>,
          TError,
          Awaited<ReturnType<typeof getTodos>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTodos<TData = Awaited<ReturnType<typeof getTodos>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 할 일 목록 조회
 */

export function useGetTodos<TData = Awaited<ReturnType<typeof getTodos>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTodosQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary 할 일 추가
 */
export const addTodo = (
    addTodoBody: AddTodoBody,
 signal?: AbortSignal
) => {
      
      
      return customFetcher<Todo>(
      {url: `/api/todos/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addTodoBody, signal
    },
      );
    }
  


export const getAddTodoMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addTodo>>, TError,{data: AddTodoBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof addTodo>>, TError,{data: AddTodoBody}, TContext> => {

const mutationKey = ['addTodo'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addTodo>>, {data: AddTodoBody}> = (props) => {
          const {data} = props ?? {};

          return  addTodo(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddTodoMutationResult = NonNullable<Awaited<ReturnType<typeof addTodo>>>
    export type AddTodoMutationBody = AddTodoBody
    export type AddTodoMutationError = unknown

    /**
 * @summary 할 일 추가
 */
export const useAddTodo = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addTodo>>, TError,{data: AddTodoBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addTodo>>,
        TError,
        {data: AddTodoBody},
        TContext
      > => {

      const mutationOptions = getAddTodoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary 할 일 수정
 */
export const updateTodo = (
    id: number,
    updateTodoBody: UpdateTodoBody,
 ) => {
      
      
      return customFetcher<Todo>(
      {url: `/api/todos/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateTodoBody
    },
      );
    }
  


export const getUpdateTodoMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTodo>>, TError,{id: number;data: UpdateTodoBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateTodo>>, TError,{id: number;data: UpdateTodoBody}, TContext> => {

const mutationKey = ['updateTodo'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTodo>>, {id: number;data: UpdateTodoBody}> = (props) => {
          const {id,data} = props ?? {};

          return  updateTodo(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateTodoMutationResult = NonNullable<Awaited<ReturnType<typeof updateTodo>>>
    export type UpdateTodoMutationBody = UpdateTodoBody
    export type UpdateTodoMutationError = void

    /**
 * @summary 할 일 수정
 */
export const useUpdateTodo = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTodo>>, TError,{id: number;data: UpdateTodoBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTodo>>,
        TError,
        {id: number;data: UpdateTodoBody},
        TContext
      > => {

      const mutationOptions = getUpdateTodoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
